<?php

/**
 * @file
 * Contains comment_limit.module..
 */

use Drupal\comment\Entity\Comment;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\field\Entity\FieldConfig;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function comment_limit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the comment_limit module.
    case 'help.page.comment_limit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Limits comments per node type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function comment_limit_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state) {
  /** @var CommentForm $comment */
  $comment = $form_state->getFormObject()->getEntity();
  $form['edit-limit-per-user'] = [
    '#type' => 'number',
    '#title' => 'Comment limit per user',
    '#weight' => 1,
    '#min' => '0',
    '#max' => '1000',
    '#default_value' => $comment->getThirdPartySetting('comment_limit', 'edit-limit-per-user', FALSE),
  ];
  $form['edit-limit-per-node'] = [
    '#type' => 'number',
    '#title' => 'Comment limit per node',
    '#weight' => 1,
    '#min' => '0',
    '#max' => '10000',
    '#default_value' => $comment->getThirdPartySetting('comment_limit', 'edit-limit-per-node', FALSE),
  ];
  $form['#entity_builders'][] = 'comment_limit_form_field_edit_form_add_form_builder';
}

/**
 * Formbuilder.
 */
function comment_limit_form_field_edit_form_add_form_builder($entity_type, FieldConfig $comment, &$form, FormStateInterface $form_state) {
  $comment->setThirdPartySetting('comment_limit', 'edit-limit-per-user', $form_state->getValue('edit-limit-per-user'));
  $comment->setThirdPartySetting('comment_limit', 'edit-limit-per-node', $form_state->getValue('edit-limit-per-node'));
}

/**
 * Implements hook_comment_insert().
 */
function comment_limit_comment_insert(Comment $comment) {
  // General variables.
  $entity_type = $comment->getCommentedEntityTypeId();
  $entity_id = $comment->getCommentedEntityId();
  $node = Node::load($comment->getCommentedEntityId());
  $bundle = $node->getType();
  $comment_type = FieldConfig::load($entity_type . '.' . $bundle . '.comment');
  // User related variables.
  $user = Drupal::currentUser();
  $maxCommmentUser = $comment_type->getThirdPartySetting('comment_limit', 'edit-limit-per-user', FALSE) + 1;
  $limitUser = $comment_type->getThirdPartySetting('comment_limit', 'edit-limit-per-user', FALSE);
  $currentCommentUser = comment_limit_get_user($entity_id);
  // Node related variables
  $maxCommentNode = $comment_type->getThirdPartySetting('comment_limit', 'edit-limit-per-node', FALSE) + 1;
  $limitNode = $comment_type->getThirdPartySetting('comment_limit', 'edit-limit-per-node', FALSE);
  $currentCommentNode = comment_limit_get_node($entity_id);

  if ($maxCommentNode) {
    if ($maxCommentNode <= $currentCommentNode && !$user->hasPermission('bypass comment limit')) {
      $comment->delete();
      drupal_set_message(t('The Node you want to comment has reached its maximum of @maxcommentnode comments', ['@maxcommentnode' => $limitNode]));
    }
  }
  if ($maxCommmentUser) {
    if ($maxCommmentUser <= $currentCommentUser && !$user->hasPermission('bypass comment limit')) {
      $comment->delete();
      drupal_set_message(t('You have commented @maxcomment times, please edit or delete some of your older comments', ['@maxcomment' => $limitUser]));
    }
  }

}

/**
 * Get user comment limit for this node type.
 */
function comment_limit_get_user($entity_id) {
  $user = Drupal::currentUser();
  $uid = $user->id();
  // Count comment of user.
  $db = \Drupal::database();
  $query = $db->select('comment_field_data', 'c')
    ->fields('c', ['entity_id', 'uid'])
    ->condition('uid', $uid)
    ->condition('entity_id', $entity_id)
    ->execute();
  $query->allowRowCount = TRUE;
  return $query->rowCount();
}

/**
 * Get node comment limit for this node type.
 */
function comment_limit_get_node($entity_id) {
  $db = Drupal::database();
  $query = $db->select('comment_entity_statistics', 'c')
    ->fields('c', ['comment_count'])
    ->condition('entity_id', $entity_id)
    ->execute()
    ->fetchField();
  return $query;
}
